Algoritmo "numero"
// Descrição   : escolha caso
// Autor(a)    : Aleff Souza
// Data atual  : 20/07/2020
Var
// Seção de Declarações das variáveis 
  numero:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite um numero inteiro de 0 a 5")
 leia(numero)
 
 escolha numero
 caso 0
 escreval("VOCE DIGITOU ZERO")
  caso 1
 escreval("VOCE DIGITOU UM")
  caso 2
 escreval("VOCE DIGITOU DOIS")
  caso 3
 escreval("VOCE DIGITOU TRES")
  caso 4
 escreval("VOCE DIGITOU QUATRO")
  caso 5
 escreval("VOCE DIGITOU CINCO")
 outrocaso
 escreval("NUMERO INVALIDO POR ESTA FORA DO PEDIDO")

 fimescolha

Fimalgoritmo