algoritmo "calculeosnumeros"
// Função :calcular o numero elevado aou quadrado
// Autor :Aleff Souza
// Data : 11/03/2020
// Seção de Declarações 
var
n1,n2,n3,n4,total:real
inicio
// Seção de Comandos 
//entrada
escreval("digite o numero 1:")
leia(n1)
escreval("digite o numero 2:")
leia(n2)
escreval("digite o numero 3:")
leia(n3)
escreval("digite o numero 4:")
leia(n4)
 //processsamento
 total<-(n1^2+n2^2+n3^2+n4^2)

 //saida
 escreval("o total de todos os numero são:",total)

fimalgoritmo
