algoritmo "conversao"
// Função :converter horas e minutos em segundos
// Autor :Aleff Souza
// Data : 18/05/2020
// Seção de Declarações 
var
 hora,minuto,total:real
inicio
// Seção de Comandos 
escreval ("digite aqui que somente as horas:")
leia(hora)
escreval ("digite aqui somente os minutos:")
leia(minuto)

total<-(minuto/60)+hora

escreval("isso sera conertido em",total,"segundos")





fimalgoritmo
