Algoritmo "idade"
// Descrição   : solicitar altura e idade e informar se pode competir ou nao
// Autor(a)    : Aleff Souza
// Data atual  : 09/06/2020
Var
idade:inteiro
resp:caracter


Inicio
//entrada
escreval("esta começado")
escreval("qual a sua idade: ")
leia(idade)
escreval("possui habilitação : ")
leia(resp)

se ((idade>=18) e( resp= "sim"))entao

escreval("pode passar")

fimse

escreval("nao pode passar, carro rebocado! ")

Fimalgoritmo
