Algoritmo "funçaõdolaçorepita"
// Descrição   : explicaão do laço de repetiçaõ repita
// Autor(a)    : Aleff Souza
// Data atual  : 02/09/2020
Var
cont,mult,soma:inteiro
Inicio
cont <-1
mult <-1
soma <-0
repita
escreval("incremento:",cont)
escreval("acumulador:",soma)
escreval("multiplicador:",mult)
cont <- cont+1 //incremento
soma <- soma + cont //acumulador
mult<- mult * cont //multiplicador

ate(cont>=6)


Fimalgoritmo