Algoritmo "SOMA"
// Descrição   : Somar os numeros
// Autor(a)    : Aleff Souza
// Data atual  : 16/09/2020
Var
// Seção de Declarações das variáveis 
cont,soma,numero:INTEIRO

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
soma<-0
para cont de 1 ate 10 passo 1 faca
  escreval("Digite um número: ")
   leia(numero)
  soma<-soma+numero
fimpara
limpatela

 escreval("O valor da SOMA entre os números é de: ",soma)


Fimalgoritmo